/* Context actions and a single docked review surface. No source geometry edits. */
(function(root){
'use strict';
function mount(){
 const $=id=>document.getElementById(id), make=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;};
 const panel=make('section');panel.id='review-tools';panel.setAttribute('aria-label','Layout review tools');$('map').append(panel);
 const status=make('p','Review data loading…');status.id='review-status';status.setAttribute('role','status');panel.append(status);
 const sections={};
 const retry=make('button','Retry saving review data');retry.type='button';retry.hidden=true;retry.onclick=()=>{try{persist();retry.hidden=true;}catch(e){status.textContent=e.message;}};panel.append(retry);
 function section(id,title){const d=make('details'),s=make('summary',title);d.id='review-section-'+id;d.append(s);panel.append(d);sections[id]=d;return d;}
 function btn(parent,id,text,fn){const b=make('button',text);b.id=id;b.type='button';b.onclick=()=>{usageEvent('ui.control',{phase:'intent',control:'review.'+(id.startsWith('show-')?'measurement-show':id.startsWith('go-')?'bookmark-go':id.startsWith('delete-')?'saved-item-delete':id.startsWith('review-diff-')?'diff-item':id)});try{if(workOrdersLoading)throw Error('Layout is loading. Wait before using review actions.');Promise.resolve(fn()).catch(e=>{status.textContent=e.message;});}catch(e){status.textContent=e.message;}};parent.append(b);return b;}
 function input(parent,id,label,type,value){const row=make('label',label),e=make('input');e.id=id;e.type=type;if(type==='checkbox')e.checked=!!value;else e.value=value;row.append(e);parent.append(row);return e;}
 function open(id){edaWorkbench.activate('review');Object.entries(sections).forEach(([key,d])=>{d.open=key===id;});if(sections[id]){sections[id].open=true;sections[id].scrollIntoView({block:'nearest'});}}
 const measurePanel=section('measure','Measurements'),measureInfo=make('p','Pick two points. Distances are in µm; angles are counter-clockwise from +X.');measurePanel.append(measureInfo);
 btn(measurePanel,'review-measure-start','Measure two points',()=>startMeasure());btn(measurePanel,'review-measure-cancel','Cancel',()=>cancelMeasure());const measureList=make('div');measureList.id='review-measure-list';measurePanel.append(measureList);
 const similarPanel=section('similar','Select similar');similarPanel.append(make('p','Select one GDS element, choose criteria, then preview. Hidden layers are excluded.'));
 const matchLayer=input(similarPanel,'review-match-layer','Same layer','checkbox',true),matchDims=input(similarPanel,'review-match-dimensions','Same bounding dimensions','checkbox',false),matchSource=input(similarPanel,'review-match-source','Same source instance','checkbox',false),tolerance=input(similarPanel,'review-tolerance','Dimension tolerance (µm)','number','0.001');tolerance.min='0';tolerance.step='any';
 btn(similarPanel,'review-similar-preview','Preview matches',previewSimilar);const applySimilar=btn(similarPanel,'review-similar-apply','Select previewed matches',()=>{if(!preview||preview.hash!==currentLayoutHash||preview.seed!==selectedFeatures.item(0)||selectedFeatures.getLength()!==1)throw Error('Selection changed; preview again.');replaceSelection(preview.features);clearOverlay();preview=null;applySimilar.disabled=true;});applySimilar.disabled=true;
 const similarResult=make('p');similarResult.id='review-similar-result';similarPanel.append(similarResult);
 [matchLayer,matchDims,matchSource,tolerance].forEach(e=>e.oninput=()=>{preview=null;applySimilar.disabled=true;clearOverlay();});
 const bookmarkPanel=section('bookmarks','View bookmarks');const bookmarkName=input(bookmarkPanel,'review-bookmark-name','Name','text','');bookmarkName.maxLength=120;btn(bookmarkPanel,'review-bookmark-save','Save current view',saveBookmark);const bookmarkList=make('div');bookmarkList.id='review-bookmark-list';bookmarkPanel.append(bookmarkList);
 const diffPanel=section('compare','Compare previous build');const diffInfo=make('p','No previous snapshot.');diffInfo.id='review-diff-info';diffPanel.append(diffInfo);const diffFilter=make('select');diffFilter.id='review-diff-filter';diffFilter.setAttribute('aria-label','Build change type');['all','added','removed','changed'].forEach(v=>{const o=make('option',v);o.value=v;diffFilter.append(o);});diffPanel.append(diffFilter);diffFilter.onchange=renderDiff;
 btn(diffPanel,'review-diff-show','Highlight changes',showDiff);btn(diffPanel,'review-overlay-clear','Clear review highlights',clearOverlay);const diffList=make('div');diffList.id='review-diff-list';diffPanel.append(diffList);
 const capturePanel=section('capture','Annotated view for AI');capturePanel.append(make('p','Save a numbered PNG with exact selected geometry in a YAML companion. The clipboard receives the file references and context. No message is sent to an agent.'));
 const captureLabels=input(capturePanel,'review-capture-labels','Number selected elements','checkbox',true);const captureButton=btn(capturePanel,'review-capture','Save view and copy AI context',capture);
 const requests=section('request','Request a change');requests.append(make('p','Creates a draft for the selected elements. Review it in the bottom composer before adding the work order.'));
 [['move','Move'],['resize','Resize'],['inspect','Change layer'],['inspect','Replace component']].forEach((pair,i)=>btn(requests,'review-request-'+i,pair[1],()=>{if(!selectedFeatures.getLength())throw Error('Select targets first.');$('intent-action').value=pair[0];if(!$('intent-text').value.trim())$('intent-text').value=pair[1]+': ';$('intent-text').focus();}));
 const relatedClear=btn($('instruction-list'),'review-related-clear','Show all work orders',()=>{relatedOrderTargets=null;relatedClear.hidden=true;if(lastWorkOrderMessage)renderInstructions(lastWorkOrderMessage);});relatedClear.hidden=true;
 let state={version:1,bookmarks:[],measurements:[]},stateReady=false,pendingState=null,measureStart=null,measuring=false,preview=null,baseline=null,diff=null,isolation=null,capturePending=null,sequence=0;
 const overlaySource=new ol.source.Vector(),overlay=new ol.layer.Vector({source:overlaySource,style:f=>new ol.style.Style({stroke:new ol.style.Stroke({color:f.get('reviewColor')||'#ffd166',width:3,lineDash:f.get('removed')?[5,4]:undefined}),fill:new ol.style.Fill({color:'rgba(255,209,102,.12)'}),text:f.get('reviewLabel')?new ol.style.Text({text:f.get('reviewLabel'),fill:new ol.style.Fill({color:'#fff'}),stroke:new ol.style.Stroke({color:'#202020',width:4})}):undefined})});overlay.setZIndex(10000);map.addLayer(overlay);
 function id(prefix){return prefix+'-'+Date.now().toString(36)+'-'+(++sequence);}
 function persist(){if(!stateReady||workOrdersLoading)throw Error('Review state is not loaded yet.');const requestId=id('review-state');pendingState=requestId;status.textContent='Saving review data…';vscode.postMessage({type:'saveReviewState',layoutHash:currentLayoutHash,requestId,state:JSON.parse(JSON.stringify(state))});}
 function clearOverlay(){overlaySource.clear();}
 function highlight(features,color,removed){features.forEach(f=>{const copy=f.clone();copy.set('reviewColor',color);copy.set('removed',!!removed);overlaySource.addFeature(copy);});}
 function geo(f){const key=String(f.get('layerKey')||f.get('layer')||'0/0').split('/');return {type:'Feature',properties:{element_id:f.get('elementId'),layer:Number(key[0]),data_type:Number(key[1]),provenance:f.get('provenance')||{}},geometry:gdsGeoJsonFmt.writeGeometryObject(f.getGeometry())};}
 function setVisibleLayers(keys){const set=new Set(keys);allFeatures.forEach(f=>f.set('visible',set.has(f.get('layerKey'))));document.querySelectorAll('.legend-row').forEach(row=>{const sw=row.querySelector('.swatch');if(sw){const shown=set.has(sw.dataset.key);sw.classList.toggle('hidden',!shown);row.setAttribute('aria-checked',String(shown));}});vectorLayer.changed();}
 function visibleLayers(){return Object.keys(layerColors).filter(k=>allFeatures.some(f=>f.get('layerKey')===k&&f.get('visible')!==false));}
 function startMeasure(coord){if(!stateReady||workOrdersLoading)throw Error('Wait for review data to load.');setMode('select');measureStart=coord?coord.slice():null;measuring=true;selectClick.setActive(false);dragBox.setActive(false);if(modifyInteraction)modifyInteraction.setActive(false);if(translateInteraction)translateInteraction.setActive(false);open('measure');measureInfo.textContent=measureStart?'Click the end point. Escape cancels.':'Click the start point, then the end point. Escape cancels.';}
 function cancelMeasure(){if(!measuring)return;measuring=false;measureStart=null;selectClick.setActive(currentMode==='select');dragBox.setActive(currentMode==='select');syncEditableDrawings();measureInfo.textContent='Measurement cancelled. Pick two points to measure again.';}
 map.on('singleclick',e=>{if(!measuring)return;if(!measureStart){measureStart=e.coordinate.slice();measureInfo.textContent='Click the end point.';return;}const record={id:id('measure'),a:measureStart,b:e.coordinate.slice(),layoutHash:currentLayoutHash||''};cancelMeasure();state.measurements.push(record);if(state.measurements.length>200)state.measurements.shift();persist();renderState();showMeasurement(record);});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&measuring){e.preventDefault();e.stopImmediatePropagation();cancelMeasure();}},true);
 function showMeasurement(m){clearOverlay();const f=new ol.Feature(new ol.geom.LineString([m.a,m.b])),r=LayoutReview.measure(m.a,m.b);f.set('reviewLabel',r.distance.toFixed(3)+' µm');overlaySource.addFeature(f);measureInfo.textContent='ΔX '+r.dx.toFixed(3)+' · ΔY '+r.dy.toFixed(3)+' µm · '+r.distance.toFixed(3)+' µm · '+r.angle.toFixed(2)+'°'+(m.layoutHash!==currentLayoutHash?' · From an earlier layout':'');}
 function previewSimilar(){const fs=selectedFeatures.getArray();if(fs.length!==1||fs[0].get('isDrawn'))throw Error('Select exactly one GDS element.');if(matchSource.checked&&!LayoutReview.provenanceKey(geo(fs[0])))throw Error('Selected element has no unambiguous source instance. Choose layer or dimensions instead.');const tol=Number(tolerance.value);if(tolerance.value.trim()===''||!Number.isFinite(tol)||tol<0)throw Error('Enter a non-negative dimension tolerance.');const ids=LayoutReview.similar(allFeatures.filter(f=>f.get('visible')!==false).map(geo),geo(fs[0]),{layer:matchLayer.checked,dimensions:matchDims.checked,source:matchSource.checked,tolerance:tol});const wanted=new Set(ids);preview={hash:currentLayoutHash,seed:fs[0],features:allFeatures.filter(f=>wanted.has(f.get('elementId')))};clearOverlay();highlight(preview.features,'#5edfff');similarResult.textContent=preview.features.length+' matches. Selection is unchanged until you apply.';applySimilar.disabled=false;}
 function saveBookmark(){if(!stateReady)throw Error('Wait for review data to load.');const name=bookmarkName.value.trim()||'View '+(state.bookmarks.length+1);state.bookmarks.push({id:id('view'),name,center:map.getView().getCenter().slice(),resolution:map.getView().getResolution(),rotation:map.getView().getRotation(),visibleLayers:visibleLayers()});if(state.bookmarks.length>100)state.bookmarks.shift();persist();renderState();bookmarkName.value='';open('bookmarks');}
 function renderState(){measureList.replaceChildren();state.measurements.forEach(m=>{const row=make('div'),r=LayoutReview.measure(m.a,m.b);btn(row,'show-'+m.id,r.distance.toFixed(3)+' µm'+(m.layoutHash!==currentLayoutHash?' · earlier layout':''),()=>showMeasurement(m));btn(row,'delete-'+m.id,'×',()=>{state.measurements=state.measurements.filter(x=>x.id!==m.id);persist();renderState();clearOverlay();}).setAttribute('aria-label','Delete measurement');measureList.append(row);});bookmarkList.replaceChildren();state.bookmarks.forEach(b=>{const row=make('div'),name=make('input');name.value=b.name;name.maxLength=120;name.setAttribute('aria-label','Bookmark name');row.append(name);name.onchange=()=>{const value=name.value.trim();if(value){b.name=value;persist();}else name.value=b.name;};btn(row,'go-'+b.id,'Go',()=>{map.getView().setCenter(b.center);map.getView().setResolution(b.resolution);map.getView().setRotation(b.rotation);setVisibleLayers(b.visibleLayers);});btn(row,'delete-'+b.id,'×',()=>{state.bookmarks=state.bookmarks.filter(x=>x.id!==b.id);persist();renderState();}).setAttribute('aria-label','Delete bookmark');bookmarkList.append(row);});}
 function diffRows(){if(!diff)return [];return [...diff.added.map(f=>({kind:'added',after:f})),...diff.removed.map(f=>({kind:'removed',before:f})),...diff.changed.map(f=>({kind:'changed',...f}))].filter(r=>diffFilter.value==='all'||r.kind===diffFilter.value);}
 function featureFromGeo(f){return gdsGeoJsonFmt.readFeature(f);}
 function showDiff(){clearOverlay();diffRows().forEach(r=>{if(r.before)highlight([featureFromGeo(r.before)],'#ff7777',true);if(r.after)highlight([featureFromGeo(r.after)],r.kind==='added'?'#69df9c':'#ffd166');});}
 function renderDiff(){diffList.replaceChildren();if(!baseline||!Array.isArray(baseline.features)){diff=null;diffInfo.textContent=baseline?.status||'No previous snapshot. Rebuild after this version has been saved.';return;}diff=LayoutReview.compare(baseline.features,allFeatures.map(geo));diffInfo.textContent=diff.added.length+' added · '+diff.removed.length+' removed · '+diff.changed.length+' changed · '+diff.unchanged+' unchanged. Red: previous; green/yellow: current. Source-ambiguous edits appear as added/removed.';const rows=diffRows();rows.slice(0,200).forEach((r,i)=>btn(diffList,'review-diff-'+i,r.kind+' · '+((r.after||r.before).properties?.element_id||i),()=>{clearOverlay();const fs=[];if(r.before){const f=featureFromGeo(r.before);fs.push(f);highlight([f],'#ff7777',true);}if(r.after){const f=featureFromGeo(r.after);fs.push(f);highlight([f],'#69df9c');}let ext=ol.extent.createEmpty();fs.forEach(f=>ol.extent.extend(ext,f.getGeometry().getExtent()));map.getView().fit(ext,{padding:[40,40,40,40],duration:0});}));if(rows.length>200)diffList.append(make('p','Showing first 200 changes; highlighting includes all.'));}
 async function capture(){if(capturePending||workOrdersLoading)return;const fs=selectedFeatures.getArray().slice();if(!fs.length)throw Error('Select elements to include exact AI context.');if(fs.length>200)throw Error('Select at most 200 elements for a readable capture.');map.renderSync();const size=map.getSize(),canvas=make('canvas');canvas.width=size[0];canvas.height=size[1];const ctx=canvas.getContext('2d');ctx.fillStyle=getComputedStyle(document.body).backgroundColor;ctx.fillRect(0,0,...size);map.getViewport().querySelectorAll('.ol-layer canvas').forEach(c=>{if(!c.width)return;ctx.save();const opacity=c.parentNode.style.opacity||c.style.opacity;ctx.globalAlpha=opacity===''?1:Number(opacity);const transform=c.style.transform;if(transform&&transform!=='none'){const m=new DOMMatrix(transform);ctx.setTransform(m.a,m.b,m.c,m.d,m.e,m.f);}else ctx.scale(c.clientWidth/c.width||1,c.clientHeight/c.height||1);ctx.drawImage(c,0,0);ctx.restore();});const labels=fs.map((f,i)=>({number:i+1,id:String(f.get('isDrawn')?f.get('annotationId'):f.get('elementId'))}));if(captureLabels.checked)fs.forEach((f,i)=>{const p=map.getPixelFromCoordinate(ol.extent.getCenter(f.getGeometry().getExtent()));ctx.fillStyle='#15202b';ctx.beginPath();ctx.arc(p[0],p[1],12,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffffff';ctx.stroke();ctx.fillStyle='#ffffff';ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(i+1),p[0],p[1]);});const requestId=id('capture');capturePending=requestId;captureButton.disabled=true;status.textContent='Choose where to save the annotated view…';try{vscode.postMessage({type:'exportReviewCapture',requestId,layoutHash:currentLayoutHash,pngDataUrl:canvas.toDataURL('image/png'),components:componentsFromFeatures(fs),request:currentIntent(),labels:captureLabels.checked?labels:[],view:{center:map.getView().getCenter(),resolution:map.getView().getResolution(),rotation:map.getView().getRotation(),size,visibleLayers:visibleLayers()}});}catch(e){capturePending=null;captureButton.disabled=false;throw e;}}
 function orderRelated(record,ids){const valid=record.tracking&&record.tracking.layoutHash===currentLayoutHash&&['current','relinked'].includes(record.tracking.status);const targets=valid?record.tracking.targetIds:record.gdsHash===currentLayoutHash?workOrderTargetIds(record):[];return targets.some(id=>ids.includes(String(id)));}
 function resetDocument(){retry.hidden=true;cancelMeasure();clearOverlay();state={version:1,bookmarks:[],measurements:[]};stateReady=false;pendingState=null;baseline=null;diff=null;preview=null;isolation=null;capturePending=null;captureButton.disabled=false;applySimilar.disabled=true;relatedClear.hidden=true;status.textContent='Review data loading…';renderState();renderDiff();}
 window.addEventListener('message',e=>{const m=e.data||{};if(m.gdsPath&&String(m.gdsPath).replace(/\\/g,'/').toLowerCase()!==currentGdsPath.replace(/\\/g,'/').toLowerCase())return;if(m.layoutHash!==undefined&&m.layoutHash!==currentLayoutHash)return;if(m.type==='reviewState'){if(m.warning){stateReady=false;status.textContent=m.warning;return;}if(!LayoutReview.validateReviewState(m.state)){status.textContent='Invalid review state; current data preserved.';return;}state=JSON.parse(JSON.stringify(m.state));stateReady=true;status.textContent='Review data loaded.';renderState();}else if(m.type==='reviewBaseline'){baseline=m;renderDiff();}else if(m.type==='reviewStateSaved'&&m.requestId===pendingState){pendingState=null;status.textContent='Review data saved.';}else if(m.type==='reviewStateError'&&m.requestId===pendingState){pendingState=null;status.textContent='Review data not saved: '+m.error;retry.hidden=false;}else if(m.type==='reviewCaptureResult'&&m.requestId===capturePending){capturePending=null;captureButton.disabled=false;status.textContent=m.ok?'Annotated view saved; AI context copied.':m.cancelled?'Capture cancelled.':'Capture failed: '+m.error;}});
 const actionLabels={'review-cancel-measure':'Cancel measurement','review-select':'Select / view ›','review-more':'Review / work orders ›','review-back':'‹ Back','review-overlap':'Choose overlapping element…','review-similar':'Select similar…','review-isolate':'Show only this layer','review-restore':'Restore layer visibility','review-related':'Related work orders','review-request':'Request a change…','review-measure':'Measure from here','review-capture-open':'Annotated view for AI…','review-bookmark':'Bookmark this location','review-open':'Review tools…','review-image-lock':'Lock image placement'};
 const menu=$('canvas-context-menu');Object.entries(actionLabels).forEach(([action,text])=>{const b=make('button',text);b.type='button';b.setAttribute('role','menuitem');b.dataset.action=action;b.hidden=true;menu.append(b);});let menuKind,menuFeature,menuPixel,hits=[];
 function menuItems(actions){menu.querySelectorAll('button[data-action]').forEach(b=>b.hidden=!actions.includes(b.dataset.action));contextMenuItems=Array.from(menu.querySelectorAll('button:not([hidden])'));const r=$('map').getBoundingClientRect();menu.style.left=Math.max(4,Math.min(parseFloat(menu.style.left)||4,r.width-menu.offsetWidth-4))+'px';menu.style.top=Math.max(4,Math.min(parseFloat(menu.style.top)||4,r.height-menu.offsetHeight-4))+'px';contextMenuItems[0]?.focus();}
 function decorateMenu(kind,feature,pixel){menuKind=kind;menuFeature=feature;menuPixel=pixel;menu.querySelectorAll('.review-overlap-item').forEach(e=>e.remove());if(measuring){menuItems(['review-cancel-measure']);return;}if(currentMode!=='select')return;hits=[];if(pixel)map.forEachFeatureAtPixel(pixel,f=>{if(!hits.includes(f))hits.push(f);},{hitTolerance:8,layerFilter:l=>l===vectorLayer||l===drawLayer});if(feature){const actions=['inspect-properties','copy-selection','new-work-order','review-related','review-select','review-more'];if(selectedFeatures.getLength()!==1)actions.shift();menuItems(actions);}else if(kind==='image'){menu.querySelector('[data-action="review-image-lock"]').textContent=microImg?.locked?'Unlock image placement':'Lock image placement';menuItems(['image-properties','review-image-lock','image-fit','image-place-global','image-place-view','image-remove']);}else menuItems(['empty-shapes','empty-route','empty-image','empty-fit','review-open',...(selectedFeatures.getLength()?['clear-selection']:[])]);}
 function contextAction(action,feature,pixel){if(!action.startsWith('review-'))return false;usageEvent('ui.control',{phase:'intent',control:'context.'+action});if(action==='review-select'){menuItems(['review-back',...(hits.length>1?['review-overlap']:[]),'review-similar',...(feature&&!feature.get('isDrawn')?['review-isolate']:[]),...(isolation?['review-restore']:[]),'fit-selection','fit-view','clear-selection',...(feature?.get('isDrawn')?['edit-drawing','delete-drawing']:[])]);return true;}if(action==='review-more'){menuItems(['review-back','review-request','review-measure','review-capture-open','review-bookmark',...(contextSourceRef(feature)?['source-navigation']:[])]);return true;}if(action==='review-back'){decorateMenu(menuKind,menuFeature,menuPixel);return true;}if(action==='review-overlap'){menuItems(['review-back']);hits.slice(0,100).forEach((f,i)=>{const b=make('button',(f.get('isDrawn')?'Drawing ':'GDS ')+(f.get('annotationId')||f.get('elementId'))+' · '+f.get('layer'));b.type='button';b.className='review-overlap-item';b.setAttribute('role','menuitem');b.onmouseenter=b.onfocus=()=>{clearOverlay();highlight([f],'#5edfff');};b.onclick=()=>{replaceSelection([f]);clearOverlay();closeCanvasContextMenu();};menu.append(b);});contextMenuItems=Array.from(menu.querySelectorAll('button:not([hidden])'));return true;}
 const coord=pixel?map.getCoordinateFromPixel(pixel):map.getView().getCenter();closeCanvasContextMenu();try{if(action==='review-cancel-measure')cancelMeasure();if(action==='review-open')open('measure');if(action==='review-similar')open('similar');if(action==='review-related'){relatedOrderTargets=selectedFeatures.getArray().map(f=>String(f.get('annotationId')||f.get('elementId')));relatedClear.hidden=false;$('work-order-search').value='';$('work-order-filter').value='all';if($('instruction-list').hidden)$('instruction-list-btn').click();edaWorkbench.activate('changes');if(lastWorkOrderMessage)renderInstructions(lastWorkOrderMessage);}if(action==='review-request')open('request');if(action==='review-measure')startMeasure(coord);if(action==='review-capture-open')open('capture');if(action==='review-bookmark')saveBookmark();if(action==='review-isolate'){if(!isolation)isolation=visibleLayers();setVisibleLayers([feature.get('layerKey')]);}if(action==='review-restore'&&isolation){setVisibleLayers(isolation);isolation=null;}if(action==='review-image-lock'&&microImg&&!imageBusy){microImg.locked=!microImg.locked;imgMoveMode=false;updateImageControls();saveImageState();}}catch(e){status.textContent=e.message;open('measure');}return true;}
 function closeContext(){if(menu.querySelector('.review-overlap-item')){clearOverlay();menu.querySelectorAll('.review-overlap-item').forEach(e=>e.remove());}}
 return {isMeasuring:()=>measuring,closeContext,resetDocument,cancelMeasure,orderRelated,decorateMenu,contextAction,open};
}
root.ReviewTools={mount};
})(window);
