const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const cp = require('child_process');
const root = path.resolve(__dirname, '../..');
const python = process.env.GDS_PYTHON || path.join(root, '.venv-fork', 'Scripts', 'python.exe');
assert(fs.existsSync(python), `gdsfactory Python runtime is required: ${python}`);
const out = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'gds-factory-reference-')), 'selection.cjs');
require('esbuild').buildSync({ entryPoints: [path.join(root, 'src/selectionExport.ts')], bundle: true, platform: 'node', format: 'cjs', outfile: out });
const { selectionDocument } = require(out);
const source = { type: 'Polygon', coordinates: [[[0, 0], [4, 0], [4, 2], [0, 2], [0, 0]]] };
const current = { type: 'Polygon', coordinates: [source.coordinates[0].map(([x, y]) => [x*Math.cos(Math.PI/6)-y*Math.sin(Math.PI/6)+3,x*Math.sin(Math.PI/6)+y*Math.cos(Math.PI/6)+5])] };
const component = { provId: 'factory-runtime', drawn: true, geometry: current, layer: '1/0', factory: {
    name: 'rectangle', settings: { size: [4, 2] }, groupId: 'runtime-group', origin: [3, 5], sourceGeometry: source, pieceIndex: 0, pieceCount: 1,
}, intent: { action: 'add', targetIds: [] } };
const code = selectionDocument('chip.gds', 'hash', [component], 'TOP').factory_references[0].code;
assert.match(code, /ref\.drotate\(/);
assert.match(code, /ref\.dmove\(/);
const result = cp.execFileSync(python, ['-c', "import sys, gdsfactory as gf; gf.gpdk.PDK.activate(); parent=gf.Component('parent'); exec(sys.stdin.read(), globals()); import math; assert abs(ref.dcenter[0]-(3+2*math.cos(math.pi/6)-math.sin(math.pi/6)))<0.002; assert abs(ref.dcenter[1]-(5+2*math.sin(math.pi/6)+math.cos(math.pi/6)))<0.002; print(len(parent.insts))"], { input: code, encoding: 'utf8' }).trim();
assert.equal(result, '1');
const projectRoot = path.dirname(out);
fs.writeFileSync(path.join(projectRoot, 'gds_components.py'), 'import gdsfactory as gf\ndef custom(size=(4,2)):\n    return gf.components.rectangle(size=size)\nCOMPONENTS={"pad":custom}\n');
const custom = JSON.parse(JSON.stringify(component));
custom.factory.name = 'project:pad';
custom.factory.library = { module: 'gds_components', exportName: 'pad' };
const customDocument = selectionDocument('chip.gds', 'hash', [custom], 'TOP');
const reference = customDocument.factory_references[0];
assert.deepEqual(reference.library, custom.factory.library);
assert.equal(reference.source_file, 'gds_components.py');
assert.deepEqual(customDocument.annotations[0].factory_proposal.library, custom.factory.library);
assert.match(reference.code, /from gds_components import COMPONENTS/);
const customResult = cp.execFileSync(python, ['-c', "import sys, gdsfactory as gf; gf.gpdk.PDK.activate(); parent=gf.Component('parent'); exec(sys.stdin.read(), globals()); assert len(parent.insts)==1; assert abs(ref.dcenter[0]-4.232)<0.002; print(len(parent.insts))"], { input: reference.code, cwd: projectRoot, encoding: 'utf8' }).trim();
assert.equal(customResult, '1', 'project factory recipe did not create one placed instance');
custom.geometry.coordinates[0][1][0] += 1;
const changed = selectionDocument('chip.gds', 'hash', [custom], 'TOP').factory_references[0];
assert.equal(changed.status, 'geometry_authoritative');
assert.equal(changed.code, undefined, 'deformed project geometry emitted a factory recipe');
fs.rmSync(path.dirname(out), { recursive: true, force: true });
console.log(JSON.stringify({ status: 'passed', python, checks: ['generated-reference-executes', 'post-placement-transform-api'] }));
