const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');
const { buildSync } = require('esbuild');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'gds-instruction-'));
const out = path.join(root, 'queue.cjs');
buildSync({ entryPoints: [path.join(__dirname, '../../src/instructionQueue.ts')], bundle: true, platform: 'node', format: 'cjs', outfile: out });
const { InstructionQueue } = require(out);
const input = (name) => ({ gdsPath: name, gdsHash: 'hash-' + name, request: { action: 'add', text: 'Add primitive' }, components: [] });
let q = new InstructionQueue(root);
assert.equal(q.ready(), true);
const a = q.add(input('a.gds'));
const b = q.add(input('./a.gds'));
assert.deepEqual(q.list().map(x => x.id), [a.id, b.id]);
assert.throws(() => q.setStatus(b.id, 'done'), /FIFO/);
q.setStatus(a.id, 'done', 'applied');
q.setStatus(b.id, 'done');
q = new InstructionQueue(root);
assert.deepEqual(q.list().map(x => x.status), ['done', 'done']);
assert.equal(q.get(a.id).context.schema, 'gds-navigator.selection');
const q1 = new InstructionQueue(root), q2 = new InstructionQueue(root);
const c0 = q1.add(input('c0.gds'));
assert.throws(() => q2.add(input('d.gds')), /changed externally/);
q2.reload(); const d = q2.add(input('d.gds')); q2.setStatus(c0.id, 'done'); q2.setStatus(d.id, 'done'); q.reload();
const source = path.join(root, 'source.py'); fs.writeFileSync(source, 'value = 1\n', 'utf8');
const cliQueue = path.join(root, '.gds-navigator', 'instructions.json');
const cliStart = spawnSync(process.execPath, [path.join(__dirname, '../../scripts/instructions.cjs'), '--queue', cliQueue, 'start', a.id, '--file', source], { encoding: 'utf8' });
assert.notEqual(cliStart.status, 0, 'completed instruction must not be restarted');
const c = q.add(input('c.gds')); const cliStart2 = spawnSync(process.execPath, [path.join(__dirname, '../../scripts/instructions.cjs'), '--queue', cliQueue, 'start', c.id, '--file', source], { encoding: 'utf8' });
assert.equal(cliStart2.status, 0, cliStart2.stderr); fs.writeFileSync(source, 'value = 2\n', 'utf8');
const cliDone = spawnSync(process.execPath, [path.join(__dirname, '../../scripts/instructions.cjs'), '--queue', cliQueue, 'done', c.id], { encoding: 'utf8' }); assert.equal(cliDone.status, 0, cliDone.stderr);
const cliRevert = spawnSync(process.execPath, [path.join(__dirname, '../../scripts/instructions.cjs'), '--queue', cliQueue, 'revert', c.id], { encoding: 'utf8' }); assert.equal(cliRevert.status, 0, cliRevert.stderr); assert.equal(fs.readFileSync(source, 'utf8'), 'value = 1\n');
const invalid = path.join(root, 'invalid.py'); fs.writeFileSync(invalid, Buffer.from([0xff, 0xfe])); q.reload(); const e = q.add(input('e.gds')); assert.throws(() => q.start(e.id, [invalid]), /UTF-8|utf-8/);
const file = q.location;
const before = fs.readFileSync(file, 'utf8');
fs.writeFileSync(file, '{ malformed');
const bad = new InstructionQueue(root);
assert.equal(bad.ready(), false);
assert.equal(fs.readFileSync(file, 'utf8'), '{ malformed');
fs.writeFileSync(file, before);
console.log(JSON.stringify({ status: 'passed', checks: ['fifo', 'reopen', 'context', 'external-conflict', 'reload', 'malformed-preservation'] }));
