const assert = require('assert');
const review = require('../../webview/layout-review.js');
const feature = (id, x, source, data_type = 0) => ({ type: 'Feature', properties: { element_id: id, layer: 1, data_type, ...(source ? { provenance: source } : {}) }, geometry: { type: 'LineString', coordinates: [[x, 0], [x + 2, 0]] } });
const src = { file: 'a.py', instance_name: 'u1', array_index: 0, loop_index: 1, call_chain: ['top', 'u'] };
const moveSrc = { file: 'a.py', instance_name: 'move', array_index: 0, loop_index: 1, call_chain: ['top', 'u'] };
assert.deepEqual(review.measure([1, 2], [-2, 6]), { dx: -3, dy: 4, distance: 5, angle: 126.86989764584402 });
assert.throws(() => review.measure([Infinity, 0], [0, 0]));
const seed = feature('s', 0, src);
assert.deepEqual(review.similar([seed, feature('x', 0, src)], seed, { source: true }), ['s', 'x']);
assert.deepEqual(review.similar([feature('x', 0)], seed, { source: true }), []);
assert.throws(() => review.similar([], seed, {}));
assert.deepEqual(review.similar([feature('dt', 0, src, 1)], seed, { layer: true }), []);
const polyA = { type: 'Feature', properties: { element_id: 'pa', layer: 1, data_type: 0 }, geometry: { type: 'Polygon', coordinates: [[[0, 0], [2, 0], [2, 2], [0, 2], [0, 0]]] } };
const polyB = { ...polyA, properties: { ...polyA.properties, element_id: 'pb' }, geometry: { type: 'Polygon', coordinates: [[[2, 2], [2, 0], [0, 0], [0, 2], [2, 2]]] } };
assert.equal(review.compare([polyA], [polyB]).unchanged, 1);
const before = [feature('old', 0), feature('dup-a', 5), feature('dup-b', 5), feature('move', 10, moveSrc), feature('amb1', 20, src), feature('amb2', 30, src)];
const after = [feature('new', 0), feature('dup-c', 5), feature('moved', 11, moveSrc), feature('amb3', 21, src), feature('amb4', 31, src)];
const diff = review.compare(before, after);
assert.equal(diff.unchanged, 2);
assert.equal(diff.changed.length, 1);
assert.equal(diff.changed[0].before.properties.element_id, 'move');
assert.deepEqual(diff.added.map(f => f.properties.element_id), ['amb3', 'amb4']);
assert.deepEqual(diff.removed.map(f => f.properties.element_id), ['dup-b', 'amb1', 'amb2']);
assert.equal(review.validateReviewState({ version: 1, bookmarks: [{ id: 'b', name: 'n', center: [0, 0], resolution: 2, rotation: 360, visibleLayers: ['1/0'] }], measurements: [{ id: 'm', a: [0, 0], b: [1, 1], layoutHash: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef' }] }), true);
assert.equal(review.validateReviewState({ version: 1, bookmarks: [{ id: 'b', name: 'n', center: [0, 0], resolution: 0, rotation: 0, visibleLayers: [] }], measurements: [] }), false);
assert.equal(review.validateReviewState({ version: 1, bookmarks: [], measurements: [{ id: 'm', a: [0, 0], b: [Infinity, 1], layoutHash: '' }] }), false);
assert.equal(review.validateReviewState({ version: 1, bookmarks: Array.from({ length: 101 }, (_, i) => ({ id: 'b' + i, name: 'n', center: [0, 0], resolution: 1, rotation: 0, visibleLayers: [] })), measurements: [] }), false);
const many = Array.from({ length: 10000 }, (_, i) => feature('f' + i, i));
assert.equal(review.compare(many.slice().reverse(), many).unchanged, 10000);
const ring = Array.from({ length: 10000 }, (_, i) => [i, i % 17]); ring.push(ring[0]);
const rotated = ring.slice(4000, -1).concat(ring.slice(0, 4000)); rotated.push(rotated[0]);
assert.equal(review.compare([{ type: 'Feature', properties: { layer: 1, data_type: 0 }, geometry: { type: 'Polygon', coordinates: [ring] } }], [{ type: 'Feature', properties: { layer: 1, data_type: 0 }, geometry: { type: 'Polygon', coordinates: [rotated.reverse()] } }]).unchanged, 1);
console.log(JSON.stringify({ status: 'passed', checks: ['measurement', 'similarity-scope', 'canonical-multiset-diff', 'provenance-ambiguity', 'state-validation'] }));
