#!/usr/bin/env node
'use strict';
const assert = require('assert/strict');
const cp = require('child_process');
const fs = require('fs');
const http = require('http');
const path = require('path');
const puppeteer = require('puppeteer-core');
const ROOT = path.resolve(__dirname, '../..');
const BROWSER = [process.env.GDS_BROWSER, 'C:/Program Files/Microsoft Edge/Application/msedge.exe', 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', 'C:/Program Files/Google/Chrome/Application/chrome.exe'].filter(Boolean).find(fs.existsSync);
assert(BROWSER, 'Edge/Chrome required; set GDS_BROWSER');
const TINY = { type: 'FeatureCollection', features: [{ type: 'Feature', properties: { element_id: 'target-a', layer: 1, data_type: 0, color: '#f38ba8' }, geometry: { type: 'Polygon', coordinates: [[[0, 0], [8, 0], [8, 8], [0, 8], [0, 0]]] } }] };
function startServer() { return new Promise(resolve => { const server = http.createServer((req, res) => { const p = new URL(req.url, 'http://127.0.0.1').pathname; let body, type; if (p === '/tiny.json') { body = JSON.stringify(TINY); type = 'application/json'; } else { const file = path.resolve(ROOT, p.replace(/^\/+/, '')); if ((file !== ROOT && !file.startsWith(ROOT + path.sep)) || !fs.existsSync(file) || !fs.statSync(file).isFile()) { res.writeHead(404); return res.end('not found'); } body = fs.readFileSync(file); type = ({ '.html': 'text/html; charset=utf-8', '.js': 'text/javascript', '.css': 'text/css' }[path.extname(file).toLowerCase()] || 'application/octet-stream'); } res.writeHead(200, { 'Content-Type': type, 'Cache-Control': 'no-store' }); res.end(body); }); server.listen(0, '127.0.0.1', () => resolve({ server, port: server.address().port })); }); }
async function main() {
  cp.execFileSync(process.execPath, [path.join(ROOT, 'scripts/make-standalone.js')], { cwd: ROOT, stdio: 'inherit', windowsHide: true });
  const out = path.join(ROOT, 'logs/reliability/manhattan-route'); fs.mkdirSync(out, { recursive: true }); const { server, port } = await startServer(); const browser = await puppeteer.launch({ executablePath: BROWSER, headless: true, args: ['--no-first-run'] });
  try {
    const page = await browser.newPage(); await page.setViewport({ width: 1400, height: 950 }); const errors = []; page.on('pageerror', e => errors.push(e.message)); await page.goto(`http://127.0.0.1:${port}/webview/test-standalone.html?data=/tiny`, { waitUntil: 'networkidle0' }); await page.waitForFunction(() => allFeatures.length === 1); await page.evaluate(() => { currentLayoutHash = 'hash-a'; map.updateSize(); map.getView().fit([0, 0, 40, 40], { size: map.getSize(), padding: [80, 80, 80, 80], duration: 0 }); map.renderSync(); });
    const point = async xy => page.evaluate(c => { const p = map.getPixelFromCoordinate(c), r = map.getTargetElement().getBoundingClientRect(); return [p[0] + r.left, p[1] + r.top]; }, xy);
    const target = await point([4, 4]); await page.mouse.click(target[0], target[1]); await page.waitForFunction(() => selectedFeatures.getLength() === 1 && !selectedFeatures.item(0).get('isDrawn'));
    await page.click('[data-mode="route"]'); assert.equal(await page.$eval('[data-mode="route"]', el => el.classList.contains('active')), true);
    for (const xy of [[10, 10], [20, 14], [30, 24]]) { const p = await point(xy); await page.mouse.click(p[0], p[1]); }
    await page.keyboard.press('Enter'); await page.waitForFunction(() => drawSource.getFeatures().some(f => f.get('route'))); const created = await page.evaluate(() => { const f = drawSource.getFeatures().find(x => x.get('route')); return { geometry: f.getGeometry().getCoordinates(), route: f.get('route'), intent: f.get('intent') }; });
    const orthogonal = coordinates => coordinates.slice(1).every((p, i) => p[0] === coordinates[i][0] || p[1] === coordinates[i][1]); assert(orthogonal(created.geometry)); assert.equal(created.route.version, 1); assert.equal(created.route.width, 1); assert.deepEqual(created.route.layer, [4, 0]); assert.equal(created.route.horizontalFirst, true); assert(created.intent.targetIds.includes('target-a'), 'route lost selected GDS target context');
    await page.evaluate(() => { const f = drawSource.getFeatures().find(x => x.get('route')); replaceSelection([f]); const target = map.getTargetElement(); target.tabIndex = 0; target.focus(); document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Tab', bubbles: true, cancelable: true })); }); await page.waitForFunction(() => document.getElementById('route-controls') && !document.getElementById('route-controls').hidden);
    // OpenLayers delays singleclick by 250ms to distinguish double-click. Let the
    // final waypoint selection finish before entering property edits.
    await new Promise(resolve=>setTimeout(resolve,350)); await page.$eval('#route-points', el => { el.value = '[[5,5],[15,12],[25,20]]'; }); await page.$eval('#route-width', el => { el.value = '2'; }); await page.$eval('#route-layer', el => { el.value = '9/2'; }); await page.$eval('#route-order', el => { el.value = 'v'; }); await page.click('#route-apply'); await page.evaluate(() => { map.updateSize(); map.renderSync(); });
    const tuned = await page.evaluate(() => { const f = drawSource.getFeatures().find(x => x.get('route')); return { coordinates: f.getGeometry().getCoordinates(), route: f.get('route'), ui: { width: document.getElementById('route-width').value, layer: document.getElementById('route-layer').value, order: document.getElementById('route-order').value, error: document.getElementById('route-error').textContent } }; }); assert(orthogonal(tuned.coordinates)); assert.equal(tuned.route.width, 2, JSON.stringify(tuned)); assert.deepEqual(tuned.route.layer, [9, 2]); assert.equal(tuned.route.horizontalFirst, false);
    await page.click('#route-move-segment'); const beforeDrag = await page.evaluate(() => drawSource.getFeatures().find(x => x.get('route')).getGeometry().getCoordinates()); const segmentMid = await page.evaluate(() => { const c = drawSource.getFeatures().find(x => x.get('route')).getGeometry().getCoordinates(), p = map.getPixelFromCoordinate([(c[0][0] + c[1][0]) / 2, (c[0][1] + c[1][1]) / 2]), r = map.getTargetElement().getBoundingClientRect(); return [p[0] + r.left, p[1] + r.top]; }); fs.writeFileSync(path.join(out, 'drag-diagnostic.json'), JSON.stringify(await page.evaluate(p=>({point:p,mapRect:map.getTargetElement().getBoundingClientRect().toJSON(),hit:document.elementFromPoint(...p)?.outerHTML.slice(0,300),size:map.getSize(),active:routeSegmentPointer.getActive()}),segmentMid),null,2));await page.screenshot({path:path.join(out,'before-drag.png')});await page.mouse.move(segmentMid[0], segmentMid[1]); await page.mouse.down(); await page.mouse.move(segmentMid[0] + 35, segmentMid[1], { steps: 4 }); await page.mouse.up(); await new Promise(resolve => setTimeout(resolve, 80)); const afterDrag = await page.evaluate(() => drawSource.getFeatures().find(x => x.get('route')).getGeometry().getCoordinates()); assert(orthogonal(afterDrag)); assert.notDeepEqual(afterDrag, beforeDrag, 'segment drag did not move route');
    await page.click('#route-move-segment'); const cancelBefore = await page.evaluate(() => drawSource.getFeatures().find(x => x.get('route')).getGeometry().getCoordinates()); const cancelPoint = await page.evaluate(() => { const c = drawSource.getFeatures().find(x => x.get('route')).getGeometry().getCoordinates(), p = map.getPixelFromCoordinate(c[1]), r = map.getTargetElement().getBoundingClientRect(); return [p[0] + r.left, p[1] + r.top]; }); await page.mouse.move(cancelPoint[0], cancelPoint[1]); await page.mouse.down(); await page.mouse.move(cancelPoint[0] + 20, cancelPoint[1] + 20, { steps: 2 }); await page.keyboard.press('Escape'); await page.mouse.up(); await new Promise(resolve => setTimeout(resolve, 40)); assert.deepEqual(await page.evaluate(() => drawSource.getFeatures().find(x => x.get('route')).getGeometry().getCoordinates()), cancelBefore);
    const saved = await page.evaluate(() => window.__sent.filter(m => m.type === 'saveAnnotations').at(-1).annotations.find(a => a.route)); assert(saved && saved.route); await page.evaluate(a => window.dispatchEvent(new MessageEvent('message', { data: { type: 'restoreAnnotations', layoutHash: 'hash-a', annotations: [a] } })), saved); assert(await page.evaluate(() => drawSource.getFeatures().some(f => f.get('route') && f.get('route').width === 2)));
    await page.evaluate(() => { const f = drawSource.getFeatures().find(x => x.get('route')); replaceSelection([f]); document.getElementById('intent-text').value = 'export route'; copyYAML(); }); const exported = await page.evaluate(() => window.__sent.filter(m => m.type === 'exportYaml').at(-1)); assert(exported.components.some(c => c.route && c.route.width === 2));
    await page.screenshot({ path: path.join(out, 'viewer.png') }); assert.deepEqual(errors, []); fs.writeFileSync(path.join(out, 'report.json'), JSON.stringify({ status: 'passed', waypointRoute: true, numericEdit: true, segmentDrag: true, cancel: true, persisted: true, exported: true }, null, 2)); console.log('Manhattan route browser interactions passed');
  } finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
