const assert = require('assert/strict');
const fs = require('fs');
const path = require('path');
const os = require('os');
const cp = require('child_process');
const { buildSync } = require('esbuild');
const root = path.resolve(__dirname, '../..');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'gds-route-export-'));
buildSync({ entryPoints: [path.join(root, 'src/selectionExport.ts')], bundle: true, platform: 'node', outfile: path.join(tmp, 'export.js') });
const { validateAnnotations, selectionDocument, toYaml } = require(path.join(tmp, 'export.js'));
const route = { version: 1, horizontalFirst: true, width: 0.75, layer: [9, 2] };
const line = { type: 'LineString', coordinates: [[-4.5, -2], [3.25, -2], [3.25, 6.125]] };
const annotation = { id: 'route-a', shapeType: 'route', geometry: line, route, intent: { action: 'add', text: 'Route this trace.', targetIds: [] } };
assert.equal(validateAnnotations([annotation]), true);
assert.equal(validateAnnotations([{ ...annotation, route: { ...route, width: -1 } }]), false);
assert.equal(validateAnnotations([{ ...annotation, route: { ...route, width: NaN } }]), false);
assert.equal(validateAnnotations([{ ...annotation, route: { ...route, layer: [9, 70000] } }]), false);
assert.equal(validateAnnotations([{ ...annotation, route: undefined }]), false);
assert.equal(validateAnnotations([{ ...annotation, geometry: { type: 'LineString', coordinates: [[0, 0], [1, 2]] } }]), false);
assert.equal(validateAnnotations([{ id: 'ordinary', geometry: { type: 'Point', coordinates: [-2, 3] } }]), true);
const doc = selectionDocument('route.gds', 'hash-route', [{ ...annotation, provId: annotation.id, drawn: true }], 'TOP');
const exported = doc.annotations[0];
assert.deepEqual(exported.route, route);
assert.deepEqual(exported.geometry, line);
assert.deepEqual(exported.route_convention, { geometry: 'Manhattan centerline', units: 'um', width: 'full trace width', corners: 'centerline bends with round stroke joins for clearance; no photonic bend radius or port attachment inferred', validation: 'angle constraints only on export; automatic clearance check is against the detected obstacles at planning time, not a fabrication or connectivity check' });
assert.equal(doc.handoff.status, 'context_complete');
const bad = selectionDocument('route.gds', 'hash-route', [{ ...annotation, provId: 'bad', drawn: true, route: { ...route, width: -2 } }], 'TOP');
assert.equal(bad.annotations[0].target_status, 'invalid_route');
assert.equal(bad.handoff.status, 'needs_clarification');
const yaml = toYaml(doc);
assert.equal(cp.execFileSync('python', ['-c', 'import sys,yaml; d=yaml.safe_load(sys.stdin.read()); assert d["annotations"][0]["route"]["layer"] == [9,2]; assert d["annotations"][0]["geometry"]["coordinates"][0][0] == -4.5; print("ok")'], { input: yaml, encoding: 'utf8' }).trim(), 'ok');
console.log(JSON.stringify({ status: 'passed', checks: ['exact-route-validation', 'invalid-route-rejection', 'negative-width', 'nan', 'layer-range', 'missing-metadata', 'route-export', 'yaml-roundtrip', 'ordinary-shape-compatibility'] }));
