const assert = require('assert');
const fs = require('fs');
const path = require('path');
const primitives = require(path.join(__dirname, '../../webview/layout-primitives.js'));
const { buildSync } = require('esbuild');
const os = require('os');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'gds-primitives-'));
buildSync({ entryPoints: [path.join(__dirname, '../../src/selectionExport.ts')], bundle: true, platform: 'node', outfile: path.join(tmp, 'export.js') });
const exporter = require(path.join(tmp, 'export.js'));

const spec = { version: 1, kind: 'taper', length: 10.25, width1: 2.5, width2: 4.75, layer: [17, 3], origin: [-4.125, 2.75], rotationDeg: 90 };
assert.equal(primitives.validate(spec), true);
assert.equal(primitives.validate({ ...spec, kind: 'straight', width2: 3 }), false);
const g = primitives.geometry(spec);
assert.equal(g.type, 'Polygon');
assert.equal(g.coordinates[0].length, 5);
assert.deepEqual(g.coordinates[0][0], [-2.875, 2.75]);
assert.deepEqual(g.coordinates[0][4], g.coordinates[0][0]);
assert(Math.abs(Math.abs(g.coordinates[0][1][0] - g.coordinates[0][0][0]) - 1.125) < 1e-12);
assert(Math.abs(Math.abs(g.coordinates[0][1][1] - g.coordinates[0][0][1]) - 10.25) < 1e-12);
const exact = primitives.describe(spec, g);
assert.equal(exact.parameter_status, 'exact');
assert.deepEqual(exact.recipe.layer, [17, 3]);
assert.deepEqual(exact.recipe.points, g.coordinates[0]);
const moved = { type: 'Polygon', coordinates: [g.coordinates[0].map(([x, y]) => [x + 3.25, y - 1.5])] };
const translated = primitives.describe(spec, moved);
assert.equal(translated.parameter_status, 'translated');
assert.deepEqual(translated.primitive.origin, [spec.origin[0] + 3.25, spec.origin[1] - 1.5]);
const exportedTranslated = exporter.selectionDocument('chip.gds', 'hash', [{ provId: 'translated', drawn: true, geometry: moved, layer: '17/3', primitive: spec, intent: { action: 'add', targetIds: [] } }], 'TOP');
assert.equal(exportedTranslated.annotations[0].parameter_status, 'translated');
assert.deepEqual(exportedTranslated.annotations[0].primitive.origin, translated.primitive.origin);
assert.deepEqual(exportedTranslated.annotations[0].construction_recipe.layer, [17, 3]);
const edited = { type: 'Polygon', coordinates: [moved.coordinates[0].map(([x, y], i) => i === 2 ? [x + .1, y] : [x, y])] };
const modified = primitives.describe(spec, edited);
assert.equal(modified.parameter_status, 'modified_geometry');
assert.equal(Object.prototype.hasOwnProperty.call(modified, 'primitive'), false);
assert.deepEqual(modified.recipe.points, edited.coordinates[0]);
const exportedEdited = exporter.selectionDocument('chip.gds', 'hash', [{ provId: 'edited', drawn: true, geometry: edited, layer: '17/3', primitive: spec, intent: { action: 'add', targetIds: [] } }], 'TOP');
assert.equal(exportedEdited.annotations[0].parameter_status, 'modified_geometry');
assert.equal(Object.prototype.hasOwnProperty.call(exportedEdited.annotations[0], 'primitive'), false);
assert.deepEqual(exportedEdited.annotations[0].construction_recipe.layer, [17, 3]);

const annotation = { provId: 'draw-primitive', drawn: true, geometry: g, layer: [17, 3], primitive: spec,
    meta: { source: 'test' }, intent: { action: 'add', text: 'recreate', targetIds: [] } };
const doc = exporter.selectionDocument('chip.gds', 'hash', [annotation], 'TOP');
assert.deepEqual(doc.annotations[0].target_layer, [17, 3]);
assert.deepEqual(doc.annotations[0].construction_recipe.points, g.coordinates[0]);
assert.deepEqual(doc.annotations[0].component_metadata, { source: 'test' });
assert.equal(doc.handoff.status, 'context_complete');
assert.equal(exporter.validateAnnotations([{ id: 'a', geometry: g, primitive: spec }]), true);
assert.equal(exporter.validateAnnotations([{ id: 'a', geometry: g, primitive: { ...spec, layer: [1, 70000] } }]), false);
const yaml = exporter.toYaml(doc);
const roundtrip = require('child_process').execFileSync('python', ['-c', 'import sys,yaml; yaml.safe_load(sys.stdin.read()); print("ok")'], { input: yaml, encoding: 'utf8' }).trim();
assert.equal(roundtrip, 'ok');

const addedVertex=JSON.parse(JSON.stringify(edited));
addedVertex.coordinates[0].splice(1,0,[(addedVertex.coordinates[0][0][0]+addedVertex.coordinates[0][1][0])/2,addedVertex.coordinates[0][0][1]+.25]);
const vertexDoc=exporter.selectionDocument('chip.gds','hash',[{...annotation,geometry:addedVertex}]);
assert.equal(vertexDoc.annotations[0].parameter_status,'modified_geometry');
assert.deepEqual(vertexDoc.annotations[0].construction_recipe.points,addedVertex.coordinates[0]);
assert.equal(vertexDoc.annotations[0].primitive,undefined);
const holeDoc=exporter.selectionDocument('chip.gds','hash',[{...annotation,geometry:{type:'Polygon',coordinates:[g.coordinates[0],g.coordinates[0]]}}]);
assert.equal(holeDoc.handoff.status,'needs_clarification');
assert.equal(holeDoc.annotations[0].construction_recipe,undefined);
assert.throws(()=>primitives.geometry({...spec,length:1e308,origin:[1e308,1e308],rotationDeg:0}),/finite numeric range/);
console.log(JSON.stringify({ status: 'passed', checks: ['geometry', 'rotation', 'translation', 'manual-edit', 'layer-and-recipe', 'yaml-roundtrip', 'corrupt-metadata'] }));
