const assert=require('assert/strict'),fs=require('fs'),path=require('path'),os=require('os'),Module=require('module');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'gds-review-provider-')),bundle=fs.mkdtempSync(path.join(os.tmpdir(),'gds-review-bundle-'));
require('esbuild').buildSync({entryPoints:[path.join(__dirname,'../../src/gdsEditor.ts')],bundle:true,platform:'node',external:['vscode'],outfile:path.join(bundle,'provider.js')});
let clipboard='',savePath,saveGate,saveEntered,markEntered,cancelNext=false;const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';const vscode={Uri:{file:fsPath=>({fsPath})},window:{createTextEditorDecorationType:()=>({}),showSaveDialog:async()=>{if(markEntered)markEntered();if(saveGate)await saveGate;if(cancelNext){cancelNext=false;return undefined}return savePath?{fsPath:savePath}:undefined},showErrorMessage(){},showWarningMessage(){},showInformationMessage(){},setStatusBarMessage(){}},workspace:{workspaceFolders:[{uri:{fsPath:root}}],getWorkspaceFolder:()=>({uri:{fsPath:root}})},env:{getPython:()=>path.join(root,'Python Env','python.exe'),clipboard:{writeText:async x=>{clipboard=x},readText:async()=>clipboard}},OverviewRulerLane:{Right:4},ConfigurationTarget:{Workspace:1,Global:2}};
const oldLoad=Module._load;let Provider;try{Module._load=function(n,...a){if(n==='vscode')return vscode;if(n==='child_process')return{spawn:()=>{const{EventEmitter}=require('events'),p=new EventEmitter();p.stdin={on(){return this},end(){setImmediate(()=>p.emit('close',0))}};p.kill=()=>{};return p}};return oldLoad.call(this,n,...a)};Provider=require(path.join(bundle,'provider.js')).GdsEditorProvider}finally{Module._load=oldLoad}
const values=new Map(),provider=new Provider({extensionUri:{fsPath:path.resolve(__dirname,'../..')},globalStorageUri:{fsPath:path.join(root,'global')},workspaceState:{get:(k,d)=>values.has(k)?values.get(k):d,update:async(k,v)=>values.set(k,v)}},{getPython:()=>path.join(root,'Python Env','python.exe')},{appendLine(){},show(){}}),hash='a'.repeat(64),gdsPath=path.join(root,'chip.gds');fs.writeFileSync(gdsPath,'gds');
const entry={gdsPath,gdsHash:hash,topCell:'TOP',loading:false,ready:true,disposed:false,lastSelection:[],elementCatalog:[],posts:[],panel:{webview:{postMessage:async m=>(entry.posts.push(m),true)}}};
const component={provId:'pad-1',layer:'1/0',bbox:[0,0,2,2],geometry:{type:'Polygon',coordinates:[[[0,0],[2,0],[2,2],[0,0]]]},provenance:{}};const key='gdsNavigator.reviewState.v1:'+path.resolve(gdsPath);const state={version:1,bookmarks:[{id:'b1',name:'origin',center:[0,0],resolution:1,rotation:0,visibleLayers:['1/0']}],measurements:[]};
async function capture(comps,labels,target){entry.posts.length=0;if(!entry.elementCatalog.length)entry.elementCatalog=[component];savePath=target||path.join(root,'capture-'+Math.random().toString(16).slice(2)+'.png');return provider.onMessage(entry,{type:'exportReviewCapture',requestId:'capture',layoutHash:hash,pngDataUrl:'data:image/png;base64,'+png,components:comps,labels,view:{zoom:3}}).then(()=>entry.posts.at(-1))}
(async()=>{try{
 await provider.onMessage(entry,{type:'saveReviewState',requestId:'ok',layoutHash:hash,state});assert.deepEqual(provider.state.get(key),state);
 await provider.onMessage(entry,{type:'saveReviewState',requestId:'bad',layoutHash:hash,state:{version:1,bookmarks:[{id:'dup',name:'x',center:[NaN,0],resolution:1,rotation:0,visibleLayers:[]},{id:'dup',name:'x',center:[0,0],resolution:1,rotation:0,visibleLayers:[]}],measurements:[]}});assert.deepEqual(provider.state.get(key),state);assert(entry.posts.some(m=>m.type==='reviewStateError'));
 let result=await capture([component],[{number:1,id:'pad-1'}]);assert.equal(result.ok,true,JSON.stringify(result));assert(fs.existsSync(savePath));assert(fs.existsSync(savePath.replace(/\.png$/,'.yaml')));
 entry.elementCatalog=[{...component,geometry:{type:'Point',coordinates:[9,9]}}];result=await capture([{...component,geometry:{type:'Point',coordinates:[99,99]}}],[{number:1,id:'pad-1'}]);assert.equal(result.ok,true);assert(!fs.readFileSync(savePath.replace(/\.png$/,'.yaml'),'utf8').includes('[99,99]'));
 const drawing={id:'draw-1',geometry:{type:'Polygon',coordinates:[[[0,0],[1,0],[1,1],[0,0]]]},intent:{action:'add',text:'proposal',targetIds:[]}};await provider.state.update('gdsNavigator.annotations.v1:'+gdsPath,[drawing]);result=await capture([{provId:'draw-1',drawn:true}],[{number:1,id:'draw-1'}]);assert.equal(result.ok,true);
 result=await capture([component],[]);assert.equal(result.ok,true,'labels may be omitted when UI numbering is disabled');
 result=await capture([component],[{number:1,id:'pad-1'},{number:2,id:'pad-1'}]);assert.equal(result.ok,false);
 savePath=path.join(root,'existing.png');fs.writeFileSync(savePath,'preserve');result=await capture([component],[{number:1,id:'pad-1'}],savePath);assert.equal(result.ok,false);assert.equal(fs.readFileSync(savePath,'utf8'),'preserve');
 savePath=path.join(root,'yaml-collision.png');fs.writeFileSync(savePath.replace(/\.png$/,'.yaml'),'preserve-yaml');result=await capture([component],[{number:1,id:'pad-1'}],savePath);assert.equal(result.ok,false);assert.equal(fs.readFileSync(savePath.replace(/\.png$/,'.yaml'),'utf8'),'preserve-yaml');assert(!fs.existsSync(savePath));
 savePath=undefined;cancelNext=true;result=await capture([component],[{number:1,id:'pad-1'}]);assert.equal(result.cancelled,true);
 let release;savePath=path.join(root,'stale.png');saveGate=new Promise(r=>release=r);saveEntered=new Promise(r=>markEntered=r);const pending=capture([component],[{number:1,id:'pad-1'}],savePath);await saveEntered;entry.gdsHash='b'.repeat(64);release();result=await pending;assert.equal(result.ok,false);assert(!fs.existsSync(savePath));saveEntered=undefined;markEntered=undefined;
 console.log(JSON.stringify({status:'passed',statePreserved:true,captureSidecars:true,hostGeometry:true,staleGuard:true,collisionGuard:true,duplicateLabelGuard:true}));
}finally{await provider.shutdownUsage();fs.rmSync(bundle,{recursive:true,force:true});fs.rmSync(root,{recursive:true,force:true})}})().catch(e=>{console.error(e.stack);process.exitCode=1});
