#!/usr/bin/env node
'use strict';
const assert = require('assert/strict');
const cp = require('child_process');
const fs = require('fs');
const http = require('http');
const path = require('path');
const puppeteer = require('puppeteer-core');
const ROOT = path.resolve(__dirname, '../..');
const BROWSER = [process.env.GDS_BROWSER, 'C:/Program Files/Microsoft Edge/Application/msedge.exe', 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', 'C:/Program Files/Google/Chrome/Application/chrome.exe'].filter(Boolean).find(fs.existsSync);
assert(BROWSER, 'Edge/Chrome required; set GDS_BROWSER');
const TINY = { type: 'FeatureCollection', features: [
  ['target-a', 1, 0, 0, 18, 18], ['target-b', 2, 24, 0, 12, 10], ['target-c', 3, -20, 0, 8, 14]
].map(([element_id, layer, x, y, w, h]) => ({ type: 'Feature', properties: { element_id, layer, data_type: 0, color: '#89b4fa' }, geometry: { type: 'Polygon', coordinates: [[[x, y], [x + w, y], [x + w, y + h], [x, y + h], [x, y]]] } })) };
function startServer() { return new Promise(resolve => { const server = http.createServer((req, res) => { const p = new URL(req.url, 'http://127.0.0.1').pathname; let body, type; if (p === '/tiny.json') { body = JSON.stringify(TINY); type = 'application/json'; } else { const file = path.resolve(ROOT, p.replace(/^\/+/, '')); if ((file !== ROOT && !file.startsWith(ROOT + path.sep)) || !fs.existsSync(file) || !fs.statSync(file).isFile()) { res.writeHead(404); return res.end('not found'); } body = fs.readFileSync(file); type = ({ '.html': 'text/html; charset=utf-8', '.js': 'text/javascript', '.css': 'text/css' }[path.extname(file).toLowerCase()] || 'application/octet-stream'); } res.writeHead(200, { 'Content-Type': type, 'Cache-Control': 'no-store' }); res.end(body); }); server.listen(0, '127.0.0.1', () => resolve({ server, port: server.address().port })); }); }
async function main(){
 cp.execFileSync(process.execPath,[path.join(ROOT,'scripts/make-standalone.js')],{cwd:ROOT,stdio:'inherit',windowsHide:true});
 const out=path.join(ROOT,'logs/reliability/review-tools');fs.mkdirSync(out,{recursive:true});const {server,port}=await startServer();const browser=await puppeteer.launch({executablePath:BROWSER,headless:true,args:['--no-first-run']});let page;
 try{page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.setViewport({width:1400,height:900});await page.goto(`http://127.0.0.1:${port}/webview/test-standalone.html?data=/tiny`,{waitUntil:'networkidle0'});await page.waitForFunction(()=>allFeatures.length===3);
 const send=m=>page.evaluate(m=>window.dispatchEvent(new MessageEvent('message',{data:m})),m);
 await page.evaluate(()=>currentLayoutHash='a'.repeat(64));await send({type:'reviewState',gdsPath:'standalone.gds',layoutHash:'a'.repeat(64),state:{version:1,bookmarks:[],measurements:[]}});
 const b=a=>'#canvas-context-menu [data-action="'+a+'"]';
 async function point(c,button='right'){const p=await page.evaluate(c=>{map.renderSync();const p=map.getPixelFromCoordinate(c),r=map.getTargetElement().getBoundingClientRect();return [p[0]+r.left,p[1]+r.top];},c);await page.mouse.click(...p,{button});if(button==='right')await page.waitForSelector('#canvas-context-menu',{visible:true});}
 await point([9,9]);assert(await page.$$eval('#canvas-context-menu button:not([hidden])',xs=>xs.length<=7));await page.click(b('review-more'));await page.click(b('review-request'));await page.click('#review-request-0');assert.equal(await page.$eval('#intent-action',e=>e.value),'move');assert.match(await page.$eval('#intent-text',e=>e.value),/Move/);assert.equal(await page.evaluate(()=>__sent.filter(m=>m.type==='queueInstruction').length),0,'request draft submitted itself');
 await point([9,9]);await page.click(b('review-select'));await page.click(b('review-isolate'));assert.deepEqual(await page.evaluate(()=>allFeatures.filter(f=>f.get('visible')!==false).map(f=>f.get('elementId'))),['target-a']);await point([9,9]);await page.click(b('review-select'));await page.click(b('review-restore'));assert.equal(await page.evaluate(()=>allFeatures.filter(f=>f.get('visible')!==false).length),3);
 // Overlapping proposal must be explicitly selectable and previewed.
 await page.evaluate(()=>{const f=allFeatures[0].clone();f.set('elementId','overlap');source.addFeature(f);allFeatures.push(f);});await point([9,9]);await page.click(b('review-select'));await page.click(b('review-overlap'));assert.equal(await page.$$('.review-overlap-item').then(x=>x.length),2);await page.hover('.review-overlap-item');await page.click('.review-overlap-item');assert.equal(await page.evaluate(()=>selectedFeatures.getLength()),1);
 await page.evaluate(()=>{const f=allFeatures.find(f=>f.get('elementId')==='overlap');source.removeFeature(f);allFeatures=allFeatures.filter(x=>x!==f);replaceSelection([allFeatures[0]]);});
 await point([9,9]);await page.click(b('review-select'));await page.click(b('review-similar'));await page.click('#review-similar-preview');assert.match(await page.$eval('#review-similar-result',e=>e.textContent),/1 matches/);await page.click('#review-match-layer');await page.click('#review-match-dimensions');await page.click('#review-similar-preview');await page.click('#review-similar-apply');assert.equal(await page.evaluate(()=>selectedFeatures.getLength()),1);
 const order={id:'WO-RELATED',sequence:1,status:'open',gdsPath:'standalone.gds',gdsHash:'a'.repeat(64),components:[{provId:'target-a'}],request:{targetIds:['target-a'],text:'Related'},context:{}};await send({type:'instructions',gdsPath:'standalone.gds',records:[order,{...order,id:'WO-OTHER',sequence:2,components:[{provId:'target-b'}],request:{targetIds:['target-b'],text:'Other'}}]});await point([9,9]);await page.click(b('review-related'));assert.equal(await page.$$('.work-order-card').then(x=>x.length),1);await page.click('#review-related-clear');assert.equal(await page.$$('.work-order-card').then(x=>x.length),2);
 await point([9,9]);await page.click(b('review-more'));await page.click(b('review-measure'));await point([12,13],'left');await page.waitForFunction(()=>document.getElementById('review-measure-list').children.length===1);const state=await page.evaluate(()=>__sent.filter(m=>m.type==='saveReviewState').at(-1).state);assert(Math.hypot(state.measurements[0].a[0]-9,state.measurements[0].a[1]-9)<.1);assert(Math.abs(state.measurements[0].b[0]-12)<.1);
 await page.evaluate(()=>reviewTools.open('bookmarks'));await page.type('#review-bookmark-name','Pad view');await page.click('#review-bookmark-save');const saved=await page.evaluate(()=>__sent.filter(m=>m.type==='saveReviewState').at(-1).state);assert.equal(saved.bookmarks[0].name,'Pad view');await page.$eval('#review-bookmark-list input',e=>{e.value='Renamed';e.dispatchEvent(new Event('change',{bubbles:true}));});assert.equal(await page.evaluate(()=>__sent.filter(m=>m.type==='saveReviewState').at(-1).state.bookmarks[0].name),'Renamed');
 await send({type:'reviewState',gdsPath:'standalone.gds',layoutHash:'a'.repeat(64),state:{version:1,bookmarks:'bad',measurements:[]}});assert.equal(await page.$eval('#review-bookmark-list input',e=>e.value),'Renamed');
 await send({type:'reviewBaseline',gdsPath:'standalone.gds',layoutHash:'a'.repeat(64),previousHash:'old',status:'available',features:TINY.features.slice(0,2)});await page.evaluate(()=>reviewTools.open('compare'));assert.match(await page.$eval('#review-diff-info',e=>e.textContent),/1 added/);await page.click('#review-diff-show');await page.screenshot({path:path.join(out,'review-sidebar.png')});
 await page.evaluate(()=>{replaceSelection([allFeatures[0]]);reviewTools.open('capture');});await page.click('#review-capture');const capture=await page.evaluate(()=>__sent.filter(m=>m.type==='exportReviewCapture').at(-1));assert(capture,await page.$eval('#review-status',e=>e.textContent));assert(capture.pngDataUrl.startsWith('data:image/png;base64,'));assert.deepEqual(capture.labels,[{number:1,id:'target-a'}]);assert.equal(capture.components[0].provId,'target-a');fs.writeFileSync(path.join(out,'annotated-view.png'),Buffer.from(capture.pngDataUrl.split(',')[1],'base64'));await send({type:'reviewCaptureResult',requestId:capture.requestId,ok:true});assert.match(await page.$eval('#review-status',e=>e.textContent),/copied/);
 await send({type:'loadGds',gdsPath:'other.gds',layoutHash:'b'.repeat(64),geojson:TINY,annotations:[],mode:'full'});assert.equal(await page.$$('#review-bookmark-list input').then(x=>x.length),0);await send({type:'reviewState',gdsPath:'standalone.gds',layoutHash:'a'.repeat(64),state:saved});assert.equal(await page.$$('#review-bookmark-list input').then(x=>x.length),0);await send({type:'loadGds',gdsPath:'standalone.gds',layoutHash:'a'.repeat(64),geojson:TINY,annotations:[],mode:'full'});await send({type:'reviewState',gdsPath:'standalone.gds',layoutHash:'a'.repeat(64),state:saved});assert.equal(await page.$eval('#review-bookmark-list input',e=>e.value),'Pad view');
 await page.evaluate(()=>{const c=document.createElement('canvas');c.width=40;c.height=20;insertMicroImage(c.toDataURL(),'lock-test','review-image');});await page.waitForFunction(()=>microImg&&microImg.imageId==='review-image');await page.evaluate(()=>{microImg.cx=20;microImg.cy=14;microImg.umPerPx=.1;renderMicroLayer();});
 await point([20,14]);const locked=await page.evaluate(()=>microImg.locked);await page.click(b('review-image-lock'));assert.equal(await page.evaluate(()=>microImg.locked),!locked);assert.equal(await page.$eval('#image-locked',e=>e.checked),!locked);await page.waitForFunction(()=>__sent.some(m=>m.type==='saveImageState'&&m.imageId==='review-image'));
 await page.evaluate(()=>reviewTools.open('measure'));await page.click('#review-measure-start');await point([9,9]);await page.click(b('review-cancel-measure'));assert.equal(await page.evaluate(()=>reviewTools.isMeasuring()),false);
 const ids=await page.$$eval('[id]',xs=>xs.map(x=>x.id));assert.equal(ids.length,new Set(ids).size,'duplicate DOM IDs');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({status:'passed',checks:['compact-menu','request-draft','isolate-restore','overlap-choice','similar-preview','related-orders','measurement','bookmarks-rename','invalid-state','compare','annotated-capture','document-isolation','restore','shared-image-lock','unique-controls']},null,2));console.log('Review tools browser checks passed');
 }catch(e){if(page)await page.screenshot({path:path.join(out,'failure.png')});throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
}
main().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
