#!/usr/bin/env node
'use strict';
const assert = require('assert/strict');
const cp = require('child_process');
const fs = require('fs');
const http = require('http');
const path = require('path');
const puppeteer = require('puppeteer-core');
const ROOT = path.resolve(__dirname, '../..');
const BROWSER = [process.env.GDS_BROWSER, 'C:/Program Files/Microsoft Edge/Application/msedge.exe', 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', 'C:/Program Files/Google/Chrome/Application/chrome.exe'].filter(Boolean).find(fs.existsSync);
assert(BROWSER, 'Edge/Chrome required; set GDS_BROWSER');
const TINY = { type: 'FeatureCollection', features: [
  ['target-a', 1, 0, 0, 18, 18], ['target-b', 2, 24, 0, 12, 10], ['target-c', 3, -20, 0, 8, 14]
].map(([element_id, layer, x, y, w, h]) => ({ type: 'Feature', properties: { element_id, layer, data_type: 0, color: '#89b4fa' }, geometry: { type: 'Polygon', coordinates: [[[x, y], [x + w, y], [x + w, y + h], [x, y + h], [x, y]]] } })) };
function startServer() { return new Promise(resolve => { const server = http.createServer((req, res) => { const p = new URL(req.url, 'http://127.0.0.1').pathname; let body, type; if (p === '/tiny.json') { body = JSON.stringify(TINY); type = 'application/json'; } else { const file = path.resolve(ROOT, p.replace(/^\/+/, '')); if ((file !== ROOT && !file.startsWith(ROOT + path.sep)) || !fs.existsSync(file) || !fs.statSync(file).isFile()) { res.writeHead(404); return res.end('not found'); } body = fs.readFileSync(file); type = ({ '.html': 'text/html; charset=utf-8', '.js': 'text/javascript', '.css': 'text/css' }[path.extname(file).toLowerCase()] || 'application/octet-stream'); } res.writeHead(200, { 'Content-Type': type, 'Cache-Control': 'no-store' }); res.end(body); }); server.listen(0, '127.0.0.1', () => resolve({ server, port: server.address().port })); }); }
async function main() {
  cp.execFileSync(process.execPath, [path.join(ROOT, 'scripts/make-standalone.js')], { cwd: ROOT, stdio: 'inherit', windowsHide: true });
  const out = path.join(ROOT, 'logs/reliability/work-order-selection'); fs.mkdirSync(out, { recursive: true }); const { server, port } = await startServer(); const browser = await puppeteer.launch({ executablePath: BROWSER, headless: true, args: ['--no-first-run'] });
  try {
    const page = await browser.newPage(); const errors = []; page.on('pageerror', e => errors.push(String(e.stack || e.message || e))); await page.setViewport({ width: 1400, height: 900 }); await page.goto(`http://127.0.0.1:${port}/webview/test-standalone.html?data=/tiny`, { waitUntil: 'networkidle0' }); await page.waitForFunction(() => allFeatures.length === 3);
    await page.evaluate(() => { currentLayoutHash = 'hash-a'; replaceSelection([allFeatures[1]]); });
    const drawing = { id: 'draw-a', shapeType: 'polygon', geometry: { type: 'Polygon', coordinates: [[[40, 20], [44, 20], [44, 24], [40, 20]]] }, intent: { action: 'add', text: 'draw', targetIds: [], snapshot: 'hash-a', documentPath: 'standalone.gds' } };
    await page.evaluate(a => window.dispatchEvent(new MessageEvent('message', { data: { type: 'restoreAnnotations', layoutHash: 'hash-a', annotations: [a] } })), drawing);
    const record = { id: 'WO-1', sequence: 1, status: 'open', gdsPath: 'standalone.gds', gdsHash: 'hash-a', components: [{ provId: 'target-a' }, { provId: 'draw-a', drawn: true, annotationId: 'draw-a' }], request: { targetIds: ['target-a'] }, context: { request: { target_ids: ['draw-a'] } }, history: [], comments: [] };
    await page.evaluate(record => window.dispatchEvent(new MessageEvent('message', { data: { type: 'instructions', gdsPath: 'standalone.gds', nextOpen: 'WO-1', records: [record] } })), record); await page.click('#instruction-list-btn'); await page.waitForSelector('.work-order-title');
    await page.$eval('#intent-text',el=>{el.value='Unsubmitted new order';});
    await page.click('.work-order-title');
    assert.equal(await page.$eval('#intent-text',el=>el.value),'Unsubmitted new order','highlight erased the new-order draft');
    assert.deepEqual(await page.evaluate(() => selectedFeatures.getArray().map(f => f.get('isDrawn') ? f.get('annotationId') : f.get('elementId'))), ['target-a', 'draw-a'], 'work-order title did not select exact GDS and drawing targets');
    await page.evaluate(() => replaceSelection([allFeatures[1]]));
    await page.evaluate(r => window.dispatchEvent(new MessageEvent('message', { data: { type: 'instructions', gdsPath: 'standalone.gds', records: [r] } })), { ...record, id: 'WO-STALE', gdsHash: 'hash-old' }); await page.click('.work-order-title');
    assert.deepEqual(await page.evaluate(() => selectedFeatures.getArray().map(f => f.get('elementId'))), ['target-b'], 'stale work order changed current selection');
    const missing = { ...record, id: 'WO-MISSING', components: [{ provId: 'not-present' }], request: { targetIds: ['not-present'] }, context: {} };
    await page.evaluate(r => window.dispatchEvent(new MessageEvent('message', { data: { type: 'instructions', gdsPath: 'standalone.gds', records: [r] } })), missing); await page.click('.work-order-title');
    assert.deepEqual(await page.evaluate(() => selectedFeatures.getArray().map(f => f.get('elementId'))), ['target-b'], 'missing work-order target changed current selection'); assert.match(await page.$eval('#workflow-status', el => el.textContent), /Unavailable/);
    await page.evaluate(r => window.dispatchEvent(new MessageEvent('message', { data: { type: 'instructions', gdsPath: 'other.gds', records: [r] } })), record); assert.equal(await page.$eval('.work-order-title', el => el.textContent.includes('WO-MISSING')), true, 'cross-document instructions replaced current work orders');
    await page.evaluate(r => window.dispatchEvent(new MessageEvent('message', { data: { type: 'instructions', gdsPath: 'standalone.gds', records: [r] } })), record);
    const comment = page.locator('.work-order-comment-input'); await comment.fill('Needs review'); await page.click('.work-order-comment-submit'); const sent = await page.evaluate(() => window.__sent.filter(m => m.action === 'comment').at(-1)); assert.equal(sent.type, 'instructionAction'); assert.equal(sent.id, 'WO-1'); assert.equal(sent.text, 'Needs review'); assert.match(sent.requestId, /^work-order-comment-/);
    await page.click('.work-order-comment-submit'); assert.equal(await page.evaluate(() => window.__sent.filter(m => m.action === 'comment').length), 1, 'duplicate comment submitted while pending');
    await page.evaluate(requestId => window.dispatchEvent(new MessageEvent('message', { data: { type: 'instructionError', requestId, error: 'comment rejected' } })), sent.requestId); assert.equal(await page.$eval('.work-order-comment-input', el => el.value), 'Needs review'); assert.equal(await page.$eval('.work-order-comment-submit', el => el.disabled), false);
    await page.click('.work-order-comment-submit'); const retry = await page.evaluate(() => window.__sent.filter(m => m.action === 'comment').at(-1)); await page.locator('.work-order-comment-input').fill('Next comment draft'); await page.evaluate(({id, requestId}) => window.dispatchEvent(new MessageEvent('message', { data: { type: 'instructionCommented', id, requestId } })), { id: 'WO-1', requestId: retry.requestId });
    await page.evaluate(r => window.dispatchEvent(new MessageEvent('message', { data: { type: 'instructions', gdsPath: 'standalone.gds', records: [{ ...r, comments: [{ id: 'C1', text: 'Persisted comment', createdAt: '2026-09-22T00:00:00Z' }] }] } })), record); assert.match(await page.$eval('.work-order-comments', el => el.textContent), /Persisted comment/); assert.equal(await page.$eval('.work-order-comment-input', el => el.value), 'Next comment draft','ack or refresh erased an edited comment draft');
    const relinkedGeojson = { ...TINY, features: TINY.features.map((f, i) => ({ ...f, properties: { ...f.properties, element_id: i === 0 ? 'target-new' : f.properties.element_id } })) };
    await page.evaluate(({geojson, drawing}) => window.dispatchEvent(new MessageEvent('message', { data: { type: 'loadGds', geojson, gdsPath: 'standalone.gds', layoutHash: 'hash-b', annotations: [drawing], mode: 'full' } })), { geojson: relinkedGeojson, drawing: { ...drawing, id: 'draw-new', intent: { ...drawing.intent, snapshot: 'hash-b' } } });
    const relinked = { ...record, gdsHash: 'hash-a', components: [], comments: [{ id: 'C1', text: 'Persisted comment', createdAt: '2026-09-22T00:00:00Z' }], tracking: { layoutHash: 'hash-b', status: 'relinked', targetIds: ['target-new', 'draw-new'], issues: [], matches: [{ oldId: 'target-a', newId: 'target-new', kind: 'element' }, { oldId: 'draw-a', newId: 'draw-new', kind: 'drawing' }] } };
    await page.evaluate(r => window.dispatchEvent(new MessageEvent('message', { data: { type: 'instructions', gdsPath: 'standalone.gds', records: [r] } })), relinked); await page.click('.work-order-title');
    assert.deepEqual(await page.evaluate(() => selectedFeatures.getArray().map(f => f.get('isDrawn') ? f.get('annotationId') : f.get('elementId'))), ['target-new', 'draw-new'], 'relinked tracking did not select current targets'); assert.match(await page.$eval('.work-order-tracking', el => el.textContent), /Linked after rebuild/); assert.match(await page.$eval('.work-order-comments', el => el.textContent), /Persisted comment/);
    await page.evaluate(() => replaceSelection([allFeatures[1]]));
    const needsReview = { ...relinked, tracking: { layoutHash: 'hash-b', status: 'needs_review', targetIds: ['missing-new'], issues: ['Target missing-new could not be linked.'], matches: [] } };
    await page.evaluate(r => window.dispatchEvent(new MessageEvent('message', { data: { type: 'instructions', gdsPath: 'standalone.gds', records: [r] } })), needsReview); await page.click('.work-order-title'); assert.deepEqual(await page.evaluate(() => selectedFeatures.getArray().map(f => f.get('elementId'))), ['target-b'], 'needs-review tracking changed current selection'); assert.match(await page.$eval('#workflow-status', el => el.textContent), /could not be linked/); assert.match(await page.$eval('.work-order-tracking', el => el.textContent), /Targets need review/);
    await page.evaluate(() => window.dispatchEvent(new MessageEvent('message', { data: { type: 'layoutLoading' } }))); await page.click('.work-order-title'); assert.match(await page.$eval('#workflow-status', el => el.textContent), /loading/i);
    await page.evaluate(({geojson, drawing}) => window.dispatchEvent(new MessageEvent('message', { data: { type: 'loadGds', geojson, gdsPath: 'standalone.gds', layoutHash: 'hash-b', annotations: [drawing], mode: 'full' } })), { geojson: relinkedGeojson, drawing: { ...drawing, id: 'draw-new', intent: { ...drawing.intent, snapshot: 'hash-b' } } });
    await page.evaluate(r => window.dispatchEvent(new MessageEvent('message', { data: { type: 'instructions', gdsPath: 'standalone.gds', records: [{ ...r, tracking: { ...r.tracking, status: 'current', targetIds: ['target-new', 'draw-new'], layoutHash: 'hash-b' } }] } })), relinked);
    await page.screenshot({ path: path.join(out, 'selection-comments.png') }); assert.deepEqual(errors, []); fs.writeFileSync(path.join(out, 'report.json'), JSON.stringify({ status: 'passed', exactSelection: true, staleGuard: true, missingGuard: true, crossDocumentGuard: true, tracking: ['relinked', 'needs-review', 'loading-guard'], comments: ['payload', 'duplicate-block', 'failure-draft', 'ack-preserves-edited-draft', 'persisted-display'], screenshot: 'selection-comments.png' }, null, 2)); console.log('Work-order selection and comments browser reliability passed');
  } finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
}
main().catch(error => { console.error(error.stack || error); process.exitCode = 1; });
