'use strict';
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const { CRATE, ARTIFACT, sha256, sourceHash } = require('./geometry-artifact.cjs');

const built = spawnSync(process.env.CARGO || 'cargo', ['build', '--locked', '--release', '--target', 'wasm32-unknown-unknown'], {
    cwd: CRATE, stdio: 'inherit', windowsHide: true,
});
if (built.error) throw new Error('Install Rust and the wasm32-unknown-unknown target, or set CARGO to cargo: ' + built.error.message);
if (built.status !== 0) process.exit(built.status || 1);
const target = process.env.CARGO_TARGET_DIR ? path.resolve(CRATE, process.env.CARGO_TARGET_DIR) : path.join(CRATE, 'target');
const bytes = fs.readFileSync(path.join(target, 'wasm32-unknown-unknown/release/gds_geometry_kernel.wasm'));
if (!WebAssembly.validate(bytes)) throw new Error('Rust build produced invalid WebAssembly');
const payload = { sourceSha256: sourceHash(), wasmSha256: sha256(bytes), base64: bytes.toString('base64') };
fs.mkdirSync(path.dirname(ARTIFACT), { recursive: true });
fs.writeFileSync(ARTIFACT, '// Generated by npm run build:rust; do not edit.\n' +
    '(function(root){var artifact=' + JSON.stringify(payload) + ';' +
    'if(typeof module===\'object\'&&module.exports)module.exports=artifact;' +
    'if(root)root.GdsGeometryWasm=artifact;})(globalThis);\n');
console.log(`Rust geometry kernel: ${bytes.length} Wasm bytes, source ${payload.sourceSha256}`);
